# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'photo-to-video-converter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for photo-to-video-converter
    pod 'SnapKit', '~> 5.0.0'
    pod 'TLPhotoPicker'
    pod 'DZNEmptyDataSet'

end
